### PR TITLE
chore(make): add target to run meta-service inside docker

### PR DESCRIPTION
**Pull request by subotic**
resolves DSP-1571

- make metadata-server-docker-build
- make metadata-server-docker-publish
- make metadata-server-docker-run

### CODE REVIEW

**Comment by subotic** [comment]
@BalduinLandolt @mpro7 I have finally managed to get the serving of the app working again. There is now a slight problem. The app does not work, as it expects to have the Node Json Server running, which the created Docker image does not contain. The created Docker image only contains and runs a Metadata Go Service which serves the frontend application and the db.json as it is.

So, basically we need a separate Docker image that contains the node json server, the db.json file and the frontend application.

**Comment by subotic** [comment]
I've created a Docker image for running the JSON-Server and have added everything to Bazel. I've also added the make targets to run and publish the image. There is still a small error when serving the page. @mpro7 is there maybe a problem with the paging syntax? The docker image contains the newest json-server. Maybe something changed?

**Comment by mpro7** [comment]
@subotic I can't say anything w/o knowing what the error message is ;)

**Comment by subotic** [comment]
> @subotic I can't say anything w/o knowing what the error message is ;)

@mpro7 just run it and see for yourself.

**Comment by mpro7** [comment]
@subotic just did it and both FE and BE part started w/o any errors and whole app works fine locally. Or did you mean to run something else?

**Review by mpro7 — APPROVED** [review]

**Pull request merged**
