### PR TITLE
feat(admin-service): admin service authorization (DSP-1772)

### PR DESCRIPTION
**Pull request by mdelez**
resolves DSP-1772

### CODE REVIEW

**Review by subotic — APPROVED** [review]
LGTM, thanks!

**Comment by subotic** [comment]
@mdelez Please make a note somewhere, of all the things that are now hardcoded, what configuration needs to be supplied to the app at runtime.

**Comment by mdelez** [comment]
> @mdelez Please make a note somewhere, of all the things that are now hardcoded, what configuration needs to be supplied to the app at runtime.

should I do that in the docs? I need to update them anyways

**Comment by subotic** [comment]
> > @mdelez Please make a note somewhere, of all the things that are now hardcoded, what configuration needs to be supplied to the app at runtime.
> 
> should I do that in the docs? I need to update them anyways

yes, you could maybe add something like a deployment configuration section.

**Pull request merged**
